package com.example.demo.model;

public class FileType {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column file_type.TYPE_ID
	 * @mbg.generated
	 */
	private Integer TYPE_ID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column file_type.NAME
	 * @mbg.generated
	 */
	private String NAME;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column file_type.TYPE_ID
	 * @return  the value of file_type.TYPE_ID
	 * @mbg.generated
	 */
	public Integer getTYPE_ID() {
		return TYPE_ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column file_type.TYPE_ID
	 * @param TYPE_ID  the value for file_type.TYPE_ID
	 * @mbg.generated
	 */
	public void setTYPE_ID(Integer TYPE_ID) {
		this.TYPE_ID = TYPE_ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column file_type.NAME
	 * @return  the value of file_type.NAME
	 * @mbg.generated
	 */
	public String getNAME() {
		return NAME;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column file_type.NAME
	 * @param NAME  the value for file_type.NAME
	 * @mbg.generated
	 */
	public void setNAME(String NAME) {
		this.NAME = NAME == null ? null : NAME.trim();
	}
}