DROP TABLE IF EXISTS DEMODB.FILE_TYPE;
CREATE TABLE DEMODB.FILE_TYPE (TYPE_ID INT NOT NULL PRIMARY KEY, NAME VARCHAR(256) NOT NULL);

DROP TABLE IF EXISTS DEMODB.FILE;
CREATE TABLE DEMODB.FILE (TYPE_ID INT NOT NULL PRIMARY KEY, NAME VARCHAR(256) NOT NULL, CONTENT LONGBLOB NOT NULL);
