package com.example.demo.dao;

import com.example.demo.model.FileType;
import com.example.demo.model.FileTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FileTypeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_type
	 * @mbg.generated
	 */
	long countByExample(FileTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_type
	 * @mbg.generated
	 */
	int deleteByExample(FileTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_type
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer TYPE_ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_type
	 * @mbg.generated
	 */
	int insert(FileType row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_type
	 * @mbg.generated
	 */
	int insertSelective(FileType row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_type
	 * @mbg.generated
	 */
	List<FileType> selectByExample(FileTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_type
	 * @mbg.generated
	 */
	FileType selectByPrimaryKey(Integer TYPE_ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_type
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") FileType row, @Param("example") FileTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_type
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") FileType row, @Param("example") FileTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_type
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(FileType row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_type
	 * @mbg.generated
	 */
	int updateByPrimaryKey(FileType row);
}