package com.example.demo.dao;

import com.example.demo.model.File;
import com.example.demo.model.FileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FileMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file
	 * @mbg.generated
	 */
	long countByExample(FileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file
	 * @mbg.generated
	 */
	int deleteByExample(FileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer TYPE_ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file
	 * @mbg.generated
	 */
	int insert(File row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file
	 * @mbg.generated
	 */
	int insertSelective(File row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file
	 * @mbg.generated
	 */
	List<File> selectByExampleWithBLOBs(FileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file
	 * @mbg.generated
	 */
	List<File> selectByExample(FileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file
	 * @mbg.generated
	 */
	File selectByPrimaryKey(Integer TYPE_ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") File row, @Param("example") FileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file
	 * @mbg.generated
	 */
	int updateByExampleWithBLOBs(@Param("row") File row, @Param("example") FileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") File row, @Param("example") FileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(File row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file
	 * @mbg.generated
	 */
	int updateByPrimaryKeyWithBLOBs(File row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file
	 * @mbg.generated
	 */
	int updateByPrimaryKey(File row);
}